---
- name: Install Clickhouse
  hosts: clickhouse-01
  roles: clickhouse-role
- name: Install vector  packages
  hosts: vector-01
  roles: lighthouse-role
- name: Install lighthouse
  hosts: lighthouse-01
  roles: vector-role
